### ISSUE TITLE
Unable to create new posts - "Create" button unresponsive

### ISSUE THREAD

**Issue by StealthPigeon** [SakuraIsayeki/WOWS-Karma#110]
07/09/22 17:27 Win10 Opera GX browser

https://wows-karma.com/player/502087401,1985miki

Console:

Loaded Authentication data: Object
main.2bc5c873367dc2d7.js:1 Connected to Notifications hub.
main.2bc5c873367dc2d7.js:1 Array(0)
main.2bc5c873367dc2d7.js:1 Connected to Posts hub.
502087401,1985miki:1 Uncaught (in promise) Object
502087401,1985miki:1 Uncaught (in promise) Object
502087401,1985miki:1 Uncaught (in promise) Object
502087401,1985miki:1 Uncaught (in promise) Object
502087401,1985miki:1 Uncaught (in promise) Object
502087401,1985miki:1 Uncaught (in promise) Object
502087401,1985miki:1 Uncaught (in promise) Object
2main.2bc5c873367dc2d7.js:1 blurred
502087401,1985miki:1 Uncaught (in promise) Object
502087401,1985miki:1 Uncaught (in promise) Object
502087401,1985miki:1 Uncaught (in promise) Object
502087401,1985miki:1 Uncaught (in promise) Object
502087401,1985miki:1 Uncaught (in promise) Object
2main.2bc5c873367dc2d7.js:1 blurred
main.2bc5c873367dc2d7.js:1 ERROR DOMException: Failed to set the 'value' property on 'HTMLInputElement': This input element accepts a filename, which may only be programmatically set to the empty string.
    at jv.setProperty (https://wows-karma.com/main.2bc5c873367dc2d7.js:1:159968)
    at e.setProperty (https://wows-karma.com/main.2bc5c873367dc2d7.js:1:183547)
    at e.writeValue (https://wows-karma.com/main.2bc5c873367dc2d7.js:1:184917)
    at t (https://wows-karma.com/main.2bc5c873367dc2d7.js:1:201522)
    at https://wows-karma.com/main.2bc5c873367dc2d7.js:1:206395
    at Array.forEach (<anonymous>)
    at ds.setValue (https://wows-karma.com/main.2bc5c873367dc2d7.js:1:206384)
    at ds.patchValue (https://wows-karma.com/main.2bc5c873367dc2d7.js:1:206494)
    at e.handleFileInput (https://wows-karma.com/main.2bc5c873367dc2d7.js:1:493053)
    at https://wows-karma.com/main.2bc5c873367dc2d7.js:1:494197
handleError @ main.2bc5c873367dc2d7.js:1
502087401,1985miki:1 

![image](https://user-images.githubusercontent.com/101707412/183295696-b0005e19-71bc-4b72-9e6a-419c25a5804c.png)
![image](https://user-images.githubusercontent.com/101707412/183295719-db297b22-3b93-431c-a870-0c75b629080c.png)
![image](https://user-images.githubusercontent.com/101707412/183295733-22cdd846-2c67-426f-8588-2c14a74c9583.png)

**Comment by SakuraIsayeki** [comment]
Issue should be fixed for now, but awaiting a proper solution, as mod-edit validations were disabled for now.
