### ISSUE TITLE
Deleted post counter visible to moderators

### ISSUE THREAD

**Issue by Henri-PSD** [SakuraIsayeki/WOWS-Karma#122]
**Moderation and deleted posts**
The current guidelines for WOWS Karma mandate us - the moderators - to follow a specific and pre-established criterion when issuing suspentions (AKA temporary bans) and bans (AKA permabans), in particular for a suspension to be issued a user must have had at leat 10 of its posts deleted by moderators and for a ban to be issued the amount of deleted posts needed is 20. 
This requirement however meets with the problem of the absence of a "deleted/moderated post counter" adavailable to the moderator in order to monitor more efficiently the guideline violation situation of a user therefore impeading any efficient, effective and sistematic enforcement of the aforementioned guideline as we moderators have to rely on the very fallable human memory to keep track of the infractions. 

**Moderated posts counter**
The most immediate solution to this issue would be to include in the user profile page a set of counter that show the detailed statistics for moderator edited and deleted pots for that user. These counters would only be visible to the moderators and would allow for a proper, effective and impartial application of the aforementioned guideline. 

**Long term possible developments of this feature**
Possible future developments of this feature would be a stats only dedicated page of the website being created and made accessible only to moderators to monitor editions and deletions on a server-wide basis and no longer on a individual user basis.

Thanks in advance for considering this issue and its related proposed solution

**Comment by SakuraIsayeki** [comment]
Acknowledged feature request. As we're also concurrently drafting the v0.17 version, we shoudln't bruise up the API with any extra changes. This being said, most of the data you're requesting us to develop views for are already accessible.

### Platform Bans status
  - [x] Implemented as of commit fca5d28fc5dea2cb3f8d4593e18c97b00095f279

### Mod-actions overview per player profile
 - [x] API Endpoint is already available (results from `GET /api/mod/action/list`
 - [ ] Development started for v0.16 deployment
 
 ### Mod-actions counter
 - [x] API Endpoint is already available (aggregate results from `GET /api/mod/action/list`
 - [ ] Development started for v0.16 deployment
