### ISSUE TITLE
Edit function is not working

### ISSUE THREAD

**Issue by BloodyTakao** [SakuraIsayeki/WOWS-Karma#127]
**Describe the bug**
When you try to edit a post (as user) to fix for example a typo, you correct it and by pressing submit it doesnt get refreshed and the window stays open.

**To Reproduce**
1. Go to any post you created
2. Click on Edit post
3. Edit the part you want to edit
4. Confirm that you have read the guidelines
5. Press Create

**Comment by SakuraIsayeki** [comment]
Closing issue as no reproduction elements or exception stacktrace have been provided.
