### ISSUE TITLE
Qualty of life improvement for WOWS Karma moderators

### ISSUE THREAD

**Issue by Henri-PSD** [SakuraIsayeki/WOWS-Karma#146]
**An inefficient present**
At present when executing a mod action moderators have to manually write in the text box included in the Post Edit or Delete site window the morivation and the violated guideline, increasing post moderation times and thus reducing the amount moderated. 
Similarly when a platform ban moderators have to go and manually emit it directly from the API using a relatively complex and unwieldy interface. 
Another issue and inefficiency also arises from the platform ban emission process as when evaluating which type of ban to emit there is no mod action based filter in the mod action list found in every user profile to filter such actions. 

**Opportunities for efficiency**
Adding a tickbox list of all guidelines in the mod action window would allow a moderator to tick the violated guidelines and then add additional context in the text box already present at time of writing, allowing for a faster moderation, a higher amount of moderated posts and an overall more professional and standardized moderation as all mod actions would be made upon the same format. 
Introducing a Ban site window - with the same functions and requirements present in the API - to be opened via a button included in every user's profile would allow for a faster and safer ban emission as the interface would be much more user-friendly and use of a code based chapcha action confirmation and verification system to prevent bans being emitted by mistake.
Including filter functionalities in the mod action history window present in all user profiles would allow for a faster and more effective evaluation of all ban cases and therefore for better and more accurate decisions to be emitted reducing the risk of unjust bans being issued.

**A better future**
With such changes introduced an implemented the server wide moderation would become much smoother and efficient, increasing the moderated posts rate and the professionality of the moderation team. 
Overall - in short - albeit small in entity these changes would be a major game changer for WOWS Karma's moderation team.

**Comment by SakuraIsayeki** [comment]
Closed as superseded by #160.
