### ISSUE TITLE
Unable to access post button on posts

### ISSUE THREAD

**Issue by scorpionfly31** [SakuraIsayeki/WoWS-Karma#15]
![image](https://user-images.githubusercontent.com/78534981/106873899-db16d400-66cc-11eb-80a8-502f4100aae0.png)

**Comment by DJDaemonix** [comment]
Thanks for the report.

Issue seems to be linked to browser width-height ratios, as reducing the width will impact the size of the Editor modal.

Your current workaround options are :
 - Zoom out using **CTRL -**
 - Or reduce the width of your browser, to force the mobile layout to be used. Hopefully should be more friendly to your desktop height ^^

**Comment by SakuraIsayeki** [comment]
I've deployed an S/CSS fix, which should enable scrolling on the modal. More of a workaround, this still permits scrolling in the background, so we'll have to deal with that later.

In the meantime, problem has been fixed, functionnality-wise. No server restart is necessary, and effects should be immediate. Failing that, you can force CSS refresh by hitting Ctrl+F5.

Keep me informed if anny more issues arise.
