### ISSUE TITLE
Rating of players with hidden profile is impossible

### ISSUE THREAD

**Issue by IceyJones** [SakuraIsayeki/WoWS-Karma#18]
title says it all

**Comment by SakuraIsayeki** [comment]
Greetings! Issue has been noted as an initial flaw in the library we're using for WG/Vortex API calls, which I've corrected. 

First commit 519d4222759ac2353e718162b5de5d2d8e39044a aims to introduce API support for hidden accounts.
Frontend support will follow soon in the upcoming days.
