### ISSUE TITLE
Error occurring on all-Neutral Post Flairs selection

### ISSUE THREAD

**Issue by Pepega1993** [SakuraIsayeki/WoWS-Karma#30]
A [weird error](https://cdn.discordapp.com/attachments/804736706808774727/838042643241238528/unknown.png) occurred when selecting _Neutral_ for all flairs.

**Comment by SakuraIsayeki** [comment]
Thank you for the Bug report, will be looking into it as soon as possible.

For context, please confirm details :
This happens only on ASIA ? Have you tried any other region (or can't) ?
Does this happen on New posts only, or also on Edits ?

**Comment by Pepega1993** [comment]
Only on new posts. I don't have account for other servers.

**Comment by SakuraIsayeki** [comment]
Closing this issue as no further reports have come through related to this bug. This may have been fixed by another commit.
