### ISSUE TITLE
Add Swagger documentation

### ISSUE THREAD

**Issue by Pepega1993** [SakuraIsayeki/WoWS-Karma#32]
Pls add usage documentation for Swagger because I often got myself [Jebaited ](https://cdn.discordapp.com/emojis/740931260108767262.png?v=1)with all the functions.

**Comment by SakuraIsayeki** [comment]
Thank you for the suggestion. Indeed, this is much needed, and will be added ASAP. 
Documentation will be displayed directly on API Methods, to keep things simple and consistent. 

Get a preview of the layout here : https://socialguard.net/swagger

**Comment by SakuraIsayeki** [comment]
Added in #47.
