### ISSUE TITLE
Inform users for mod-deleted posts

### ISSUE THREAD

**Issue by BloodyTakao** [SakuraIsayeki/WoWS-Karma#33]
We as mods would like to have a way, to inform users which posts got deleated and for what reason.

**Comment by SakuraIsayeki** [comment]
Thank you for the suggestion. Indeed, informing a user about his post being mod-deleted would be quite informative, and in-line with the upcoming Posts Guidelines. 

Will put in roadmap for future development.

**Comment by SakuraIsayeki** [comment]
Implemented in #52, and deployed in #54.
