### ISSUE TITLE
Scroll bug

### ISSUE THREAD

**Issue by Pepega1993** [SakuraIsayeki/WoWS-Karma#45]
If the 25/50/100 post-per-page setting is selected, there is a bug where the first 10 posts seem to **disappear** when scrolling down the page and then are replaced with the other 10 new posts. The posts should appear continuously when the page is scrolled up and down. 

[This video](https://www.youtube.com/watch?v=Z6gtSFNdZ4U) is a demonstration of this bug. Please read the video description for more details.

**Comment by SakuraIsayeki** [comment]
Thank you for the report. 

After close examination, this behaviour seems tied to the `<Virtualize />` component, recently used to save on bandwidth.
Either a fix can be deployed on Frontend, or we must consider reverting/deleting this component entirely...

**Comment by SakuraIsayeki** [comment]
Reverted Commit 54d7560b060986b426b7de9a82b0d84f8577f7d4. This should mitigate the issue until a more suitable solution is found.

**Comment by SakuraIsayeki** [comment]
Reverted in #47.
