### ISSUE TITLE
API improvement: Add listing endpoints for replays, players, and clans.

### ISSUE THREAD

**Issue by LaTrissTitude** [SakuraIsayeki/WOWS-Karma#96]
`GET /api/Replay/` should provide a listing of registered replays
`GET /api/Player/` should provide a listing of registered players
`GET /api/Clan/` should provide a listing of registered clans

**Comment by SakuraIsayeki** [comment]
Given the scale of the output, this will require us to cache the responses in-memory, to only serve them periodically.

**Comment by SakuraIsayeki** [comment]
Implemented in commit c6484d074eace92b5d84bb98e843751c347db06b, without any security or caching. We're expecting this endpoint to be seldom used, given its limited use outside of big data.

Furthermore, no in-app limiting is performed. We're expecting to implement it through the hosting infrastructures, to fine-tune control over requesting parties.
